import { StyleSheet } from 'react-native';
import { typography } from '@/theme';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: '#000',
  },
  closeBtn: {
    position: 'absolute',
    top: 56,
    left: 16,
    zIndex: 10,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingTop: 80,
    paddingBottom: 16,
  },
  image: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 10,
    maxHeight: 420,
  },
  videoBox: {
    width: '100%',
    aspectRatio: 1,
    maxHeight: 420,
    backgroundColor: '#1a1a1a',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  videoLabel: {
    fontSize: 14,
    color: '#ccc',
    fontFamily: typography.fontFamily,
  },
  docBox: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  docName: {
    fontSize: 15,
    color: '#fff',
    fontFamily: typography.fontFamily,
    textAlign: 'center',
    maxWidth: 260,
  },
  bottomBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 12,
    paddingBottom: 32,
    paddingTop: 12,
    backgroundColor: 'rgba(0,0,0,0.6)',
    gap: 10,
  },
  captionInput: {
    flex: 1,
    minHeight: 42,
    maxHeight: 108,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 21,
    paddingHorizontal: 16,
    paddingVertical: 10,
    color: '#fff',
    fontSize: 15,
    lineHeight: 22,
    fontFamily: typography.fontFamily,
  },
  sendBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#E46C53',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
