import { StyleSheet } from 'react-native';
import { typography } from '@/theme';
import type { AppColors } from '@/shared/context/AppSettingsContext';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flexDirection: 'column',
    gap: 0,
    paddingHorizontal: 8,
    paddingTop: 8,
    backgroundColor: colors.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  replyBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(228,108,83,0.1)',
    borderLeftWidth: 3,
    borderLeftColor: '#E46C53',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 4,
    marginBottom: 8,
  },
  replyBarContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  replyBarText: {
    flex: 1,
    fontSize: 13,
    color: colors.textSecondary,
    fontFamily: undefined,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
  },
  inputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: colors.background,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 8,
    minHeight: 36,
    maxHeight: 96,
    borderWidth: 1,
    borderColor: colors.border,
  },
  inputWrapFocused: {
    borderColor: '#E46C53',
    borderWidth: 1.5,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    fontFamily: typography.fontFamily,
    color: colors.text,
    padding: 0,
    margin: 0,
    lineHeight: 20,
    textAlignVertical: 'top',
    includeFontPadding: false,
    // @ts-expect-error — react-native-web only
    outlineStyle: 'none',
  },
  sendBtn: { marginBottom: 0 },
  sendBtnGrad: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  attachBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'flex-end',
  },
  attachMenu: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    marginHorizontal: 16,
    marginBottom: 16,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  attachMenuItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingVertical: 14,
    paddingHorizontal: 20,
    gap: 14,
  },
  attachMenuText: {
    fontSize: 16,
    fontFamily: typography.fontFamily,
    color: colors.text,
  },
  recordingRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 4,
    height: 36,
  },
  recordingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#E46C53',
  },
  recordingTimer: {
    fontSize: 15,
    fontFamily: typography.fontFamily,
    color: colors.text,
    fontVariant: ['tabular-nums'],
    minWidth: 44,
  },
  slideHint: {
    flex: 1,
    textAlign: 'center',
    fontSize: 13,
    fontFamily: typography.fontFamily,
    color: colors.textSecondary,
  },
  slideHintCancel: {
    color: '#ED2F3C',
    fontWeight: '600',
  },
});
